version: 2.1

orbs:
  ggshield: gitguardian/ggshield@volatile
  
workflows:
  scan_my_commits:
    jobs:
      - ggshield/scan:
          name: ggshield-scan
          base_revision: <<pipeline.git.base_revision>>
          revision: <<pipeline.git.revision>>
